### ISSUE TITLE
Error if BPF includes flow action steps

### ISSUE THREAD

**Issue by bananamufu** [carfup/XTBPlugins.PCF2BPF#5]
Hi,

I'm really excited for this tool. Should be a real time-saver.

I am getting an 'Object reference not set to an instance of an object' error for BPFs that include action steps. I only have BPFs flow action steps, so I didn't test if the error appears with custom action or workflow steps as well.

Removing the steps solves the error.
Just thought I'd let you know.

Kind regards

**Comment by carfup** [comment]
Hello @bananamufu ,

An update with a fix to your issue will be deployed this week !

**Comment by carfup** [comment]
Version 1.2022.2.3 is now available.
